### ISSUE TITLE
Duplicating controllers

### ISSUE THREAD

**Issue by JacobGray** [atosorigin/PAMM_Skeleton#1]
Controllers are added to angular partials in the PAMM Skeleton when their routes are specified in app.js. They are also added at the top of each partial using ng-controller. This causes the controller to be assigned twice, meaning that code that runs on controller initialisation (such as bindings or an init function) will be called multiple times.

Suggested solution: Remove the binding by ng-controller, leaving app.js to handle controller assignment.

**Comment by peterbrock** [comment]
Believe this was fixed when @krithel moved us to UI-Routing (https://github.com/atosorigin/PAMM_Skeleton/commit/50cb303eaaa4028a99c22cefe93382b87e5e76f8)
