### ISSUE TITLE
Home controller only calls service once, not on page load

### ISSUE THREAD

**Issue by krithel** [atosorigin/PAMM_Skeleton#3]
When the HomeController.js file is loaded, it calls the service to get the users name. This only occurs once, rather than on page load. Thus, when a user logs in, the controller calls the service to display their username, and won't recall it if they navigate out and back to the page, which can cause incorrect data if they logout, and log in with another user.

**Comment by peterbrock** [comment]
Fixed with https://github.com/atosorigin/PAMM_Skeleton/commit/ec4ed8f7e83ed12f1f0ef85400356d7091a8c60f
